import sys
from os.path import join, dirname, abspath
sys.path.append(abspath(join(dirname(__file__),"..","..")))
from utils.file_loader import load_instructions_file
from google.adk.agents import Agent 
from utils.schema_normalizer import normalize_resume_schema

def formatting_passthrough(state: dict) -> dict:
    """
    Final formatting with STRICT section attribution to prevent content duplication.
    Each data point must exist in exactly one section.
    """
    # Read from final_resume (generated by generation_agent) not raw state
    resume = state.get("final_resume", {}) or state.get("resume", {}) or {}
    
    # First normalize all list fields to ensure they are actually lists
    normalized = normalize_resume_schema(resume)
    
    # STRICT SECTION ATTRIBUTION
    
    # 1. PROFILE: Contact + role fields ONLY
    profile = resume.get("profile", {})
    if isinstance(profile, str):
        # If profile is a string, create a dict with the string as name
        normalized["profile"] = {
            "name": profile,
            "role": "",
            "email": "",
            "phone": "",
            "location": "",
            "linkedin": "",
            "github": "",
            "years": "",
        }
    elif isinstance(profile, dict):
        # Only extract contact and role fields - NO descriptions or text blocks
        normalized["profile"] = {
            "name": profile.get("name", ""),
            "role": profile.get("role", ""),
            "email": profile.get("email", ""),
            "phone": profile.get("phone", ""),
            "location": profile.get("location", ""),
            "linkedin": profile.get("linkedin", ""),
            "github": profile.get("github", ""),
            "years": profile.get("years") or profile.get("years_experience", ""),
        }
    else:
        normalized["profile"] = {
            "name": "",
            "role": "",
            "email": "",
            "phone": "",
            "location": "",
            "linkedin": "",
            "github": "",
            "years": "",
        }
    
    # 2. SUMMARY: Professional overview ONLY (string)
    # Prevent duplication: if summary is a large text block that looks like it contains
    # experience/education details, truncate or validate
    summary = normalized.get("summary", "")
    if isinstance(summary, str):
        # Summary should be a brief overview, not the full raw_text
        # Keep as-is since we removed raw_text fallback in content_generator
        normalized["summary"] = summary.strip()
    else:
        normalized["summary"] = ""
    
    # 3. EXPERIENCE: Structured entries ONLY (role, company, description, achievements)
    # Already normalized by normalize_resume_schema
    # Ensure it's a list of dicts, not raw text
    experience = normalized.get("experience", [])
    if isinstance(experience, str):
        # Should not happen after normalization, but safety check
        normalized["experience"] = []
    
    # 4. EDUCATION: Degree, institution, year ONLY
    # Ensure it's a proper list, not raw text
    education = normalized.get("education", [])
    if isinstance(education, str):
        normalized["education"] = []
    
    # 5. SKILLS: List of skills ONLY
    # Already normalized by normalize_resume_schema
    
    # 6. All other sections: Only their respective extracted content
    # projects, certificates, publications, interests, volunteering, references
    # All already normalized by normalize_resume_schema
    
    return normalized


formatting_agent = Agent(
    name="formatting_agent",
    description=load_instructions_file("agents/formatting_agent/descriptions.txt"),
     tools=[formatting_passthrough]
)